Public Class frmPrincipal

#Region "Atributos"
    'Bases de datos
    Dim categoriaPokemon() As String = {"Pokémon Semilla",
"Pokémon Semilla",
"Pokémon Semilla",
"Pokémon Lagartija",
"Pokémon Llama",
"Pokémon Llama",
"Pokémon Tortuguita",
"Pokémon Tortuga",
"Pokémon Armazón ",
"Pokémon Gusano",
"Pokémon Capullo",
"Pokémon Mariposa",
"Pokémon Oruga",
"Pokémon Capullo",
"Pokémon Abeja Veneno",
"Pokémon Pajarito",
"Pokémon Pájaro",
"Pokémon Pájaro",
"Pokémon Ratón",
"Pokémon Ratón",
"Pokémon Pajarito",
"Pokémon Pico",
"Pokémon Serpiente",
"Pokémon Cobra",
"Pokémon Ratón",
"Pokémon Ratón",
"Pokémon Ratón",
"Pokémon Ratón",
"Pokémon Pin Veneno",
"Pokémon Pin Veneno",
"Pokémon Taladro",
"Pokémon Pin Veneno",
"Pokémon Pin Veneno",
"Pokémon Taladro",
"Pokémon Hada",
"Pokémon Hada",
"Pokémon Zorro",
"Pokémon Zorro",
"Pokémon Globo",
"Pokémon Globo",
"Pokémon Murciélago",
"Pokémon Murciélago",
"Pokémon Hierbajo ",
"Pokémon Hierbajo ",
"Pokémon Flor",
"Pokémon Hongo",
"Pokémon Hongo",
"Pokémon Insecto",
"Pokémon Polilla Venenosa ",
"Pokémon Topo",
"Pokémon Topo",
"Pokémon Gato Araña",
"Pokémon Gato Fino",
"Pokémon Pato",
"Pokémon Pato",
"Pokémon Mono Cerdo",
"Pokémon Mono Cerdo",
"Pokémon Perrito",
"Pokémon Leyenda ",
"Pokémon Renacuajo",
"Pokémon Renacuajo",
"Pokémon Renacuajo",
"Pokémon Psi",
"Pokémon Psi",
"Pokémon Psi",
"Pokémon Superpoder",
"Pokémon Superpoder",
"Pokémon Superpoder",
"Pokémon Flor",
"Pokémon Matamoscas",
"Pokémon Matamoscas",
"Pokémon Medusa",
"Pokémon Medusa",
"Pokémon Roca",
"Pokémon Roca",
"Pokémon Megatón",
"Pokémon Caballo Fuego",
"Pokémon Caballo Fuego",
"Pokémon Atontado",
"Pokémon Ermitaño",
"Pokémon Imán",
"Pokémon Imán",
"Pokémon Pato Salvaje",
"Pokémon Ave Gemela",
"Pokémon Ave Triple",
"Pokémon León Marino",
"Pokémon León Marino",
"Pokémon Lodo",
"Pokémon Lodo",
"Pokémon Bivalvo",
"Pokémon Bivalvo",
"Pokémon Gas",
"Pokémon Gas",
"Pokémon Sombra",
"Pokémon Serpiente Roca ",
"Pokémon Hipnosis",
"Pokémon Hipnosis",
"Pokémon Cangrejo",
"Pokémon Tenaza",
"Pokémon Bola",
"Pokémon Bola",
"Pokémon Huevo",
"Pokémon Coco",
"Pokémon Solitario",
"Pokémon Apilahueso",
"Pokémon Patada ",
"Pokémon Puñetazo ",
"Pokémon Lametazo",
"Pokémon Gas Venenoso",
"Pokémon Gas Venenoso",
"Pokémon Clavos",
"Pokémon Taladro",
"Pokémon Huevo",
"Pokémon Enredadera",
"Pokémon Maternal ",
"Pokémon Dragón",
"Pokémon Dragón",
"Pokémon Pez Color",
"Pokémon Pez Color",
"Pokémon Estrella ",
"Pokémon Misterioso",
"Pokémon Barrera",
"Pokémon Mantis",
"Pokémon Forma Humana",
"Pokémon Eléctrico",
"Pokémon Escupefuego",
"Pokémon Escarabajo",
"Pokémon Toro Bravo",
"Pokémon Pez",
"Pokémon Atrocidad",
"Pokémon Transporte",
"Pokémon Transformación",
"Pokémon Evolución",
"Pokémon Burbuja",
"Pokémon Relámpago",
"Pokémon Llama",
"Pokémon Virtual",
"Pokémon Espiral",
"Pokémon Espiral",
"Pokémon Armazón ",
"Pokémon Armazón ",
"Pokémon Fósil",
"Pokémon Dormir",
"Pokémon Congelar",
"Pokémon Eléctrico",
"Pokémon Llama",
"Pokémon Dragón",
"Pokémon Dragón",
"Pokémon Dragón",
"Pokémon Genético",
"Pokémon Nueva Especie"}
    Dim entradasPokedex() As String = {"Una rara semilla fue plantada en su espalda al nacer. La planta brota y crece con este Pokémon.",
"Cuando el bulbo de su espalda crece, parece no poder ponerse de pie sobre sus patas traseras.",
"La planta florece cuando absorbe energía solar. Ésta le obliga a ponerse en busca de la luz solar.",
"Prefiere los sitios calientes. Dicen que cuando llueve sale vapor de la punta de su cola.",
"Cuando balancea su ardiente cola, eleva la temperatura a niveles muy altos.",
"Escupe fuego tan caliente que funde las rocas. Causa incendios forestales sin querer.",
"Tras nacer, su espalda se hincha y endurece como una concha. Echa potente espuma por la boca.",
"Se oculta en el agua para cazar a sus presas. Al nadar rápidamente, mueve sus orejas para nivelarse.",
"Un brutal Pokémon con reactores de agua en su caparazón. Éstos son usados para rápidos placajes.",
"Sus cortas patas están recubiertas de ventosas que le permiten subir incansable por muros y cuestas.",
"Este Pokémon es vulnerable al ataque cuando su concha es blanda, dejando expuesto su frágil cuerpo.",
"En combate, aletea a gran velocidad para lanzar al aire sus tóxicos polvillos.",
"Fácil de ver por los bosques comiendo hojas. Tiene un aguijón venenoso en la cabeza.",
"Casi incapaz de moverse, este Pokémon sólo puede endurecer su caparazón para protegerse.",
"Vuela muy deprisa y ataca con los venenosos y grandes aguijones de su cola y patas delanteras.",
"Muy común en bosques y selvas. Aletea al nivel del suelo para levantar la gravilla.",
"Muy protector de su amplio territorio, este Pokémon picoteará ferozmente a todo intruso.",
"Cuando caza, vuela muy deprisa a ras del agua, y sorprende a inocentes presas como Magikarp.",
"Cuando ataca lo muerde todo. Pequeño y muy rápido, es muy fácil de ver en muchos sitios.",
"Utiliza sus bigotes para equilibrarse. Parece que si son cortados va más despacio.",
"Come bichos en zona de hierba. Agita sus cortas alas muy rápido para mantenerse en el aire",
"Con sus enormes y magníficas alas, puede seguir volando sin tener que aterrizar para descansar.",
"Es muy silencioso y sigiloso. Come huevos de pájaros como los de Pidgey y Spearow.",
"Se dice que las feroces señales de alerta de su panza difieren de un área a otra.",
"Cuando varios de estos Pokémon se juntan, su energía puede causar fuertes tormentas.",
"Su larga cola le sirve para protegerse a sí mismo de su potente y alto voltaje.",
"Se oculta bajo tierra, en zonas áridas y alejadas del agua. Sólo emerge para cazar su comida.",
"Ante el peligro se acurruca en un espinoso ovillo. De esta forma puede rodar para atacar o escapar.",
"Aunque pequeñas, sus venenosas púas son muy peligrosas. La hembra tiene pequeños cuernos.",
"El cuerno de la hembra crece lentamente. Prefiere ataques físicos como arañar o morder.",
"Sus duras escamas lo protegen. Usa su gran corpulencia para ejecutar potentes movimientos.",
"Estira sus orejas para sentir el peligro. Cuanto mayores sean sus cuernos, más fuerte su veneno.",
"Un Pokémon agresivo, siempre listo para atacar. El cuerno de la cabeza segrega un potente veneno.",
"Usa su potente cola en combate para aplastar y oprimir a su presa. Después le rompe los huesos.",
"Su mágico y adorable aspecto atrae a la gente. Es raro y solo aparece en ciertas áreas.",
"Un encantador y tímido Pokémon muy raro de ver. Corre y se oculta en cuanto siente que viene gente.",
"Cuando nace sólo tiene una cola, pero a medida que crece, ésta se va dividiendo desde la punta.",
"Muy inteligente y vengativo. Agarrar una de sus colas podría causar 1000 años de maldición.",
"Cuando sus ojos se iluminan, canta una secreta melodía con la que duerme a sus enemigos.",
"Su cuerpo es blando y gomoso. Cuando se enfada traga aire y se hincha enormemente.",
"Forma colonias en lugares oscuros. Usa ultrasonidos para identificar y acercarse a los objetivos.",
"Cuando ataque, seguirá chupando energía de su victima aunque pese tanto que ya no pueda volar.",
"Durante el día entierra su cara en el suelo. Merodea por la noche plantando sus semillas.",
"El fluido que gotea de su boca no son babas. Es un néctar que usa para atraer a sus presas.",
"A mayor pétalo, más tóxico es su polen. Su cabeza es pesada y le cuesta mantenerla.",
"Cava para chupar las raíces de los árboles. Las setas de su espalda crecen a sus expensas.",
"Una pareja de parásitos en la que la seta ha ocupado al bicho. Prefieren los sitios húmedos.",
"Vive entre las sombras de altos árboles, donde come insectos. Le atrae la luz por la noche.",
"El polvillo que cubre sus alas es de distinto color según el tipo de veneno que lleve.",
"Vive un metro por debajo del suelo, donde se alimenta de raíces. También aparece en la superficie.",
"Un trío de Diglett. Causa enormes terremotos cavando 80 km por debajo del suelo.",
"Adora los objetos redondos. De noche, camina por las calles en busca de monedas perdidas.",
"Aunque es muy admirado por su pelo, es difícil de entrenar como mascota por su voluble maldad.",
"Aunque calma al enemigo con su vacía mirada, este Pokémon usará poderes psicoquinéticos.",
"Suele ser visto nadando elegante por los lagos. Es confundido con el monstruo japonés, Kappa.",
"Se enfada muy fácilmente. Puede pasar de la tranquilidad a la ira en apenas un segundo.",
"Siempre furioso y tenaz con sus patadas. Perseguirá a su presa hasta que la atrape.",
"Gran defensor de su territorio. Ladrará y morderá para echar a los intrusos de su espacio.",
"Un Pokémon muy admirado desde la antigüedad por su belleza. Corre ágilmente como si tuviera alas.",
"Sus nuevas y pequeñas patas no le dejan correr. Parece que prefiere nadar a estar de pie.",
"Capaz de vivir dentro o fuera del agua. Fuera del agua suda para mantener su cuerpo baboso.",
"Experto nadador tanto en braza como en crawl. Gana fácilmente a todo nadador humano.",
"Con su capacidad de leer la mente, detecta cualquier peligro y se teletransporta a un lugar seguro.",
"Emite ondas-alfa especiales de su cuerpo que causan jaquecas a todo aquel que se acerca.",
"Su cerebro puede ganar al de un súper-ordenador. Tiene un coeficiente intelectual de 5000.",
"Le encanta ser musculoso. Se entrena en todo tipo de arte marcial para ser aún más fuerte.",
"Su musculoso cuerpo es tan fuerte que usa un cinto anti-fuerza para controlar sus movimientos.",
"Con sus fuertes músculos, lanza bestiales puñetazos y envía a su víctima al lejano horizonte.",
"Un Pokémon carnívoro que caza insectos. Usa sus raíces para absorber humedad.",
"Escupe polvo-veneno para envenenar al enemigo, y luego lo liquida con su ácido.",
"Vive en grandes colonias en el interior de las junglas, aunque nadie ha podido verificarlo.",
"Va a la deriva a poca profundidad. Si es pescado por accidente, el castigo será su punzante ácido.",
"De tentáculos cortos, cuando caza los extiende para atrapar e inmovilizar a su presa.",
"Aparece en llanos y montañas. Semejantes a las rocas, la gente se tropieza con ellos o los pisa.",
"Se mueve rodando cuesta abajo. Rueda sobre todo obstáculo sin frenar o cambiar de dirección.",
"Su cuerpo rocoso es super duro. Soporta las explosiones de dinamita sin sufrir daño.",
"Sus cascos son 10 veces más duros que el diamante. Puede pisotear cualquier cosa en poco tiempo.",
"Muy competitivo, este Pokémon perseguirá a todo lo que se mueva rápido, esperando ganarle.",
"Increíblemente lento y torpe. Tardará 5 segundos en sentir dolor si es atacado.",
"Dicen que el Shellder pegado a la cola de Slowpoke se nutre de los residuos del anfitrión.",
"Anula la gravedad para mantenerse en el aire. Sin previo aviso usa la ondatrueno y parecidos.",
"Están formados por Magnemite unidos. Suelen aparecer cuando arden las manchas solares.",
"La ramita de cebollas verdes que lleva es su arma. Suele usarla como una espada.",
"Un pájaro que compensa su pobre vuelo caminando muy rápidamente. Deja enormes huellas.",
"Para tramar sus planes usa sus tres cerebros. Cuando 2 cabezas duermen, la otra sigue despierta.",
"El cuerno que sobresale de su cabeza es muy duro. Suele usarlo para romper el hielo.",
"Guarda energía térmica en su cuerpo. Nada a 8 nudos sin parar hasta en aguas muy frías.",
"Aparece en zonas asquerosas. Crece absorbiendo los residuos tóxicos expulsados por las fábricas.",
"Está cubierto por un repugnante lodo. Es tan tóxico que hasta sus huellas son venenosas.",
"Su caparazón repele cualquier tipo de ataque. Sólo cuando abre su caparazón es vulnerable.",
"Cuando es atacado lanza sus cuernos con gran rapidez. Sus entrañas jamás han sido vistas.",
"Casi invisible, este gaseoso Pokémon cubre al enemigo y lo adormece sin previo aviso.",
"Por su habilidad para atravesar muros de piedra, se dice que viene de otra dimensión.",
"En luna llena, a este Pokémon le gusta imitar las sombras de la gente y burlarse de sus miedos.",
"Cuando crece, las partes rocosas de su cuerpo se endurecen. Acaba pareciéndose a un diamante negro.",
"Adormece a sus enemigos y se come sus sueños. A veces se pone enfermo si come pesadillas.",
"Cuando mira al enemigo, usa una mezcla de movimientos psíquicos, como la hipnosis y la confusión.",
"Sus pinzas son potentes armas, además de usarlas para equilibrarse cuando camina lateralmente.",
"La pinza más grande tiene una enorme potencia, pero su gran tamaño la hace poco manejable.",
"Suele vivir en centrales de energía. Mucha gente muere al confundirlo con una Poké Ball.",
"Almacena energía eléctrica a gran presión. Suele explosionar ante la más mínima provocación.",
"Son muy parecidos a los huevos. Cuando se les molesta, se agrupan y atacan todos juntos.",
"Dice la leyenda que en raras ocasiones una de sus cabezas cae y sobrevive como un Exeggcute.",
"Como no se quita nunca su casco-calavera, nadie le ha visto la cara a este Pokémon.",
"El hueso que lleva es su gran arma. Lo lanza hábilmente como un boomerang dejándolos KO.",
"Si tiene prisa, sus patas se extenderán. Corre suavemente con zancadas extra-largas.",
"Aunque parezca que no hace nada, sus rápidos puñetazos-voleas son imposibles de ver.",
"Su lengua se extiende como la de un camaleón. Cuando lame a sus enemigos, éstos se estremecen.",
"Como encierra varios tipos de gases tóxicos en su cuerpo, suele explosionar sin previo aviso.",
"Donde se juntan 2 tipos de gases venenosos, 2 Koffing podrán fusionarse en un Weezing.",
"Sus huesos son 1000 veces más macizos que los humanos. Famoso por su gran fuerza.",
"Protegido por una piel tipo-escudo, puede vivir en lava líquida a 3.600 grados de temperatura.",
"Un raro y evasivo Pokémon que, según dicen, trae la felicidad a aquellos que lo atrapan.",
"Todo su cuerpo está cubierto con anchas cintas del tipo alga. Éstas se mueven cuando camina.",
"El bebé no suele salir de la segura bolsa de su madre hasta que cumple los tres años.",
"Famoso por derribar a bichos volantes lanzando tinta desde la superficie del agua.",
"Puede nadar hacia atrás moviendo rápidamente sus aletas pectorales y su robusta cola.",
"La aleta de su cola se hincha como un elegante traje de baile. Es llamado Reina del Agua.",
"En otoño, cuando se reproducen, pueden ser vistos nadando con energía por ríos y arroyos.",
"Un enigmático Pokémon que puede regenerar con facilidad todo apéndice que pierda luchando.",
"Su núcleo central brilla con los 7 colores del arco iris. Es valorado como gema por algunos.",
"Si alguien lo interrumpe mientras excava, él le abofeteará con sus enormes manos.",
"Con una agilidad y velocidad tipo ninja, puede crear la ilusión de que hay más de uno.",
"Mueve sus caderas seductoramente al caminar. Puede hacer que la gente baile al unísono.",
"Suelen andar por las centrales eléctricas, pero también merodean y causan grandes apagones.",
"Su cuerpo siempre arde con brillo naranja, con el que se oculta entre las llamas.",
"Si no consigue triturar a su víctima con sus pinzas, le dará vueltas y la arrojará lejos.",
"Cuando ve a un enemigo, carga ferozmente con su cuerpo azotando sus largas colas.",
"En un pasado lejano, era más fuerte que sus horribles descendientes de hoy en día.",
"Poco visto en la naturaleza. Enorme y malo, es capaz de destruir ciudades enteras de un ataque.",
"Un Pokémon que ha sido cazado casi hasta la extinción. Puede llevar a la gente por el agua.",
"Puede copiar el código genético de un enemigo y transformarse en una réplica de éste.",
"De irregular código genético, puede mutar si se le expone a la radiación de los elementos roca.",
"Vive cerca del agua. Su larga cola termina en una aleta muy parecida a la de una sirena.",
"Acumula iones negativos en la atmósfera para lanzar rayos de 10000 voltios de potencia.",
"Cuando almacena energía térmica en su cuerpo, su temperatura puede subir a más de 1600 grados.",
"Un Pokémon formado por códigos de programación. Se mueve libre en el ciberespacio.",
"Aunque extinto, en algunas ocasiones puede ser resucitado genéticamente de los fósiles.",
"Un prehistórico Pokémon que murió cuando su pesada concha le impidió atrapar a sus presas.",
"Un Pokémon resucitado de un fósil, encontrado en lo que hace eones fuera el fondo oceánico.",
"Con su impecable forma es un gran nadador. Corta a su presa con sus garras y absorbe sus fluidos.",
"Un prehistórico y feroz Pokémon que ataca con sus colmillos la garganta del enemigo.",
"Es muy vago. Sólo come y duerme. A medida que engorda se vuelve cada vez más perezoso.",
"Un legendario pájaro Pokémon. Se aparece a la gente que se ha perdido en las heladas montañas.",
"Un legendario pájaro Pokémon. Dicen que aparece entre las nubes lanzando enormes rayos brillantes.",
"Más conocido como el legendario pájaro de fuego. Con cada aleteo crea brillantes llamas.",
"Considerado como un mítico Pokémon durante años hasta que fue encontrada una colonia submarina.",
"Un místico Pokémon rodeado de una sutil aura y con capacidad de cambiar la climatología.",
"Un Pokémon marino que es muy raro de ver. Dicen que es tan inteligente como los humanos.",
"Fue creado por un científico tras años de horribles experimentos de ingeniería genética.",
"Es tan raro que muchos expertos opinan que es solo una ilusión. Solo unos pocos lo han visto."}
    Dim habilidades() As String = {"Espesura",
"Espesura",
"Espesura",
"Mar Llamas",
"Mar Llamas",
"Mar Llamas",
"Torrente",
"Torrente",
"Torrente",
"Polvo Escudo",
"Mudar",
"Ojo Compuesto",
"Polvo Escudo",
"Mudar",
"Enjambre",
"Vista Lince",
"Vista Lince",
"Vista Lince",
"Fuga",
"Fuga",
"Vista Lince",
"Vista Lince",
"Intimidación",
"Intimidación",
"Estática",
"Estática",
"Velo Arena",
"Velo Arena",
"Punto Tóxico",
"Punto Tóxico",
"Punto Tóxico",
"Punto Tóxico",
"Punto Tóxico",
"Punto Tóxico",
"Gran Encanto",
"Gran Encanto",
"Absorbe Fuego",
"Absorbe Fuego",
"Gran Encanto",
"Gran Encanto",
"Foco Interno",
"Foco Interno",
"Clorofila",
"Clorofila",
"Clorofila",
"Efecto Espora",
"Efecto Espora",
"Ojo Compuesto",
"Polvo Escudo",
"Velo Arena",
"Velo Arena",
"Recogida",
"Flexibilidad",
"Humedad",
"Humedad",
"Espíritu Vital",
"Espíritu Vital",
"Intimidación",
"Intimidación",
"Absorbe Agua",
"Absorbe Agua",
"Absorbe Agua",
"Sincronía",
"Sincronía",
"Sincronía",
"Agallas",
"Agallas",
"Agallas",
"Clorofila",
"Clorofila",
"Clorofila",
"Cuerpo Puro",
"Cuerpo Puro",
"Cabeza Roca",
"Cabeza Roca",
"Cabeza Roca",
"Fuga",
"Fuga",
"Despiste",
"Despiste",
"Imán",
"Imán",
"Vista Lince",
"Fuga",
"Fuga",
"Sebo",
"Sebo",
"Hedor",
"Hedor",
"Caparazón",
"Caparazón",
"Levitación",
"Levitación",
"Levitación",
"Cabeza Roca",
"Insomnio",
"Insomnio",
"Corte Fuerte",
"Corte Fuerte",
"Insonorizar",
"Insonorizar",
"Clorofila",
"Clorofila",
"Cabeza Roca",
"Cabeza Roca",
"Flexibilidad",
"Vista Lince",
"Ritmo Propio",
"Levitación",
"Levitación",
"Pararrayos",
"Pararrayos",
"Cura Natural",
"Clorofila",
"Madrugar",
"Nado Rápido",
"Punto Tóxico",
"Nado Rápido",
"Nado Rápido",
"Illuminación",
"Illuminación",
"Insonorizar",
"Enjambre",
"Despiste",
"Estática",
"Cuerpo Llama",
"Corte Fuerte",
"Intimidación",
"Nado Rápido",
"Intimidación",
"Absorbe Agua",
"Flexibilidad",
"Fuga",
"Absorbe Agua",
"Absorbe Electricidad",
"Absorbe Fuego",
"Rastro",
"Nado Rápido",
"Nado Rápido",
"Nado Rápido",
"Nado Rápido",
"Cabeza Roca",
"Inmunidad",
"Presión",
"Presión",
"Presión",
"Mudar",
"Mudar",
"Foco Interno",
"Presión",
"Sincronía"}
    Dim listaPokemones() As String = {"Bulbasaur",
"Ivysaur",
"Venusaur",
"Charmander",
"Charmeleon",
"Charizard",
"Squirtle",
"Wartortle",
"Blastoise",
"Caterpie",
"Metapod",
"Butterfree",
"Weedle",
"Kakuna",
"Beedrill",
"Pidgey",
"Pidgeotto",
"Pidgeot",
"Rattata",
"Raticate",
"Spearow",
"Fearow",
"Ekans",
"Arbok",
"Pikachu",
"Raichu",
"Sandshrew",
"Sandslash",
"Nidoran ♀",
"Nidorina",
"Nidoqueen",
"Nidoran ♂",
"Nidorino",
"Nidoking",
"Clefairy",
"Clefable",
"Vulpix",
"Ninetales",
"Jigglypuff",
"Wigglytuff",
"Zubat",
"Golbat",
"Oddish",
"Gloom",
"Vileplume",
"Paras",
"Parasect",
"Venonat",
"Venomoth",
"Diglett",
"Dugtrio",
"Meowth",
"Persian",
"Psyduck",
"Golduck",
"Mankey",
"Primeape",
"Growlithe",
"Arcanine",
"Poliwag",
"Poliwhirl",
"Poliwrath",
"Abra",
"Kadabra",
"Alakazam",
"Machop",
"Machoke",
"Machamp",
"Bellsprout",
"Weepinbell",
"Victreebel",
"Tentacool",
"Tentacruel",
"Geodude",
"Graveler",
"Golem",
"Ponyta",
"Rapidash",
"Slowpoke",
"Slowbro",
"Magnemite",
"Magneton",
"Farfetch'd",
"Doduo",
"Dodrio",
"Seel",
"Dewgong",
"Grimer",
"Muk",
"Shellder",
"Cloyster",
"Gastly",
"Haunter",
"Gengar",
"Onix",
"Drowzee",
"Hypno",
"Krabby",
"Kingler",
"Voltorb",
"Electrode",
"Exeggcute",
"Exeggutor",
"Cubone",
"Marowak",
"Hitmonlee",
"Hitmonchan",
"Lickitung",
"Koffing",
"Weezing",
"Rhyhorn",
"Rhydon",
"Chansey",
"Tangela",
"Kangaskhan",
"Horsea",
"Seadra",
"Goldeen",
"Seaking",
"Staryu",
"Starmie",
"Mr. Mime",
"Scyther",
"Jynx",
"Electabuzz",
"Magmar",
"Pinsir",
"Tauros",
"Magikarp",
"Gyarados",
"Lapras",
"Ditto",
"Eevee",
"Vaporeon",
"Jolteon",
"Flareon",
"Porygon",
"Omanyte",
"Omastar",
"Kabuto",
"Kabutops",
"Aerodactyl",
"Snorlax",
"Articuno",
"Zapdos",
"Moltres",
"Dratini",
"Dragonair",
"Dragonite",
"Mewtwo",
"Mew"}
    Dim numeroPokemon() As String = {"#001",
"#002",
"#003",
"#004",
"#005",
"#006",
"#007",
"#008",
"#009",
"#010",
"#011",
"#012",
"#013",
"#014",
"#015",
"#016",
"#017",
"#018",
"#019",
"#020",
"#021",
"#022",
"#023",
"#024",
"#025",
"#026",
"#027",
"#028",
"#029",
"#030",
"#031",
"#032",
"#033",
"#034",
"#035",
"#036",
"#037",
"#038",
"#039",
"#040",
"#041",
"#042",
"#043",
"#044",
"#045",
"#046",
"#047",
"#048",
"#049",
"#050",
"#051",
"#052",
"#053",
"#054",
"#055",
"#056",
"#057",
"#058",
"#059",
"#060",
"#061",
"#062",
"#063",
"#064",
"#065",
"#066",
"#067",
"#068",
"#069",
"#070",
"#071",
"#072",
"#073",
"#074",
"#075",
"#076",
"#077",
"#078",
"#079",
"#080",
"#081",
"#082",
"#083",
"#084",
"#085",
"#086",
"#087",
"#088",
"#089",
"#090",
"#091",
"#092",
"#093",
"#094",
"#095",
"#096",
"#097",
"#098",
"#099",
"#100",
"#101",
"#102",
"#103",
"#104",
"#105",
"#106",
"#107",
"#108",
"#109",
"#110",
"#111",
"#112",
"#113",
"#114",
"#115",
"#116",
"#117",
"#118",
"#119",
"#120",
"#121",
"#122",
"#123",
"#124",
"#125",
"#126",
"#127",
"#128",
"#129",
"#130",
"#131",
"#132",
"#133",
"#134",
"#135",
"#136",
"#137",
"#138",
"#139",
"#140",
"#141",
"#142",
"#143",
"#144",
"#145",
"#146",
"#147",
"#148",
"#149",
"#150",
"#151"}
    Dim tipo1() As String = {"Planta",
"Planta",
"Planta",
"Fuego",
"Fuego",
"Fuego",
"Agua",
"Agua",
"Agua",
"Bicho",
"Bicho",
"Bicho",
"Bicho",
"Bicho",
"Bicho",
"Normal",
"Normal",
"Normal",
"Normal",
"Normal",
"Normal",
"Normal",
"Veneno",
"Veneno",
"Eléctrico",
"Eléctrico",
"Tierra",
"Tierra",
"Veneno",
"Veneno",
"Veneno",
"Veneno",
"Veneno",
"Veneno",
"Normal",
"Normal",
"Fuego",
"Fuego",
"Normal",
"Normal",
"Veneno",
"Veneno",
"Planta",
"Planta",
"Planta",
"Bicho",
"Bicho",
"Bicho",
"Bicho",
"Tierra",
"Tierra",
"Normal",
"Normal",
"Agua",
"Agua",
"Lucha",
"Lucha",
"Fuego",
"Fuego",
"Agua",
"Agua",
"Agua",
"Psíquico",
"Psíquico",
"Psíquico",
"Lucha",
"Lucha",
"Lucha",
"Planta",
"Planta",
"Planta",
"Agua",
"Agua",
"Roca",
"Roca",
"Roca",
"Fuego",
"Fuego",
"Agua",
"Agua",
"Eléctrico",
"Eléctrico",
"Normal",
"Normal",
"Normal",
"Agua",
"Agua",
"Veneno",
"Veneno",
"Agua",
"Agua",
"Fantasma",
"Fantasma",
"Fantasma",
"Roca",
"Psíquico",
"Psíquico",
"Agua",
"Agua",
"Eléctrico",
"Eléctrico",
"Planta",
"Planta",
"Tierra",
"Tierra",
"Lucha",
"Lucha",
"Normal",
"Veneno",
"Veneno",
"Tierra",
"Tierra",
"Normal",
"Planta",
"Normal",
"Agua",
"Agua",
"Agua",
"Agua",
"Agua",
"Agua",
"Psíquico",
"Bicho",
"Hielo",
"Eléctrico",
"Fuego",
"Bicho",
"Normal",
"Agua",
"Agua",
"Agua",
"Normal",
"Normal",
"Agua",
"Eléctrico",
"Fuego",
"Normal",
"Roca",
"Roca",
"Roca",
"Roca",
"Roca",
"Normal",
"Hielo",
"Eléctrico",
"Fuego",
"Dragón",
"Dragón",
"Dragón",
"Psíquico",
"Psíquico"}
    Dim tipo2() As String = {"Veneno",
"Veneno",
"Veneno",
"",
"",
"Volador",
"",
"",
"",
"",
"",
"Volador",
"Veneno",
"Veneno",
"Veneno",
"Volador",
"Volador",
"Volador",
"",
"",
"Volador",
"Volador",
"",
"",
"",
"",
"",
"",
"",
"",
"Tierra",
"",
"",
"Tierra",
"",
"",
"",
"",
"",
"",
"Volador",
"Volador",
"Veneno",
"Veneno",
"Veneno",
"Planta",
"Planta",
"Veneno",
"Veneno",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Lucha",
"",
"",
"",
"",
"",
"",
"Veneno",
"Veneno",
"Veneno",
"Veneno",
"Veneno",
"Tierra",
"Tierra",
"Tierra",
"",
"",
"Psíquico",
"Psíquico",
"Acero",
"Acero",
"Volador",
"Volador",
"Volador",
"",
"Hielo",
"",
"",
"",
"Hielo",
"Veneno",
"Veneno",
"Veneno",
"Tierra",
"",
"",
"",
"",
"",
"",
"Psíquico",
"Psíquico",
"",
"",
"",
"",
"",
"",
"",
"Roca",
"Roca",
"",
"",
"",
"",
"",
"",
"",
"",
"Psíquico",
"",
"Volador",
"Psíquico",
"",
"",
"",
"",
"",
"Volador",
"Hielo",
"",
"",
"",
"",
"",
"",
"Agua",
"Agua",
"Agua",
"Agua",
"Volador",
"",
"Volador",
"Volador",
"Volador",
"",
"",
"Volador",
"",
""}
    Dim listaPrueba As List(Of String) = New List(Of String)

    Private _indice As Integer
#End Region

#Region "Propiedad"

    Public Property Indice As Integer
        Set(value As Integer)
            If value <> _indice Then
                _indice = value
                cargarDatos(_indice)
            End If
        End Set
        Get
            Return _indice
        End Get
    End Property
#End Region

#Region "Metodos"
    ''' <summary>
    ''' Carga los datos de la BD a los controles correspondientes
    ''' </summary>
    ''' <param name="indice"></param>
    Private Sub cargarDatos(ByVal indice As Integer)
        labNombre.Text = listaPokemones(indice)
        labNumero.Text = numeroPokemon(indice)
        labCategoria.Text = categoriaPokemon(indice)
        cargarImagen(indice)
        'Cambia el nombre de label a singular o plural
        If tipo2(indice) = "" Then
            Label6.Text = "Tipo:"
        Else
            Label6.Text = "Tipos:"
        End If
        'labTipo1.Text = tipo1(indice)
        'labTipo2.Text = tipo2(indice)
        cargarImagenTipo1(tipo1(indice))
        picTipo2.Visible = True 'Se pone true para volver a aparecer la imagen.Hay pokemones con solo 1 tipo
        cargarImagenTipo2(tipo2(indice))
        labHabilidad.Text = habilidades(indice)
        txtEntrada.Text = entradasPokedex(indice)
    End Sub

    ''' <summary>
    ''' Carga la imagen correspondiente acorde a un índice
    ''' </summary>
    ''' <param name="indice"></param>
    Private Sub cargarImagen(ByVal indice As Integer)
        Dim nombre = "pic" + CStr(indice + 1)
        picImagen.Image = My.Resources.ResourceManager.GetObject(nombre)
    End Sub

    ''' <summary>
    ''' Carga un sonido correspondiente acorde a un índice
    ''' </summary>
    ''' <param name="indice"></param>
    Private Sub cargarSonido(ByVal indice As Integer)
        Dim nombre = "cry" + CStr(indice + 1)
        My.Computer.Audio.Play(My.Resources.ResourceManager.GetObject(nombre), AudioPlayMode.WaitToComplete)
    End Sub

    Private Sub cargarImagenTipo1(ByVal tipo1 As String)
        Dim nombre = "tipo" + tipo1
        picTipo1.Image = My.Resources.ResourceManager.GetObject(nombre)
    End Sub

    Private Sub cargarImagenTipo2(ByVal tipo2 As String)
        Dim nombre = "tipo" + tipo2
        picTipo2.Image = My.Resources.ResourceManager.GetObject(nombre)
    End Sub
#End Region

#Region "Eventos"
    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles btnQuizz.Click
        frmAdivina.Show()
    End Sub

    Private Sub frmPrincipal_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Indice = 0
        For Each l As String In listaPokemones
            listaPrueba.Append(UCase(l))
        Next
        lstNumero.SelectedIndex = Indice
        cargarDatos(Indice)
    End Sub

    Private Sub lstNumero_SelectedIndexChanged(sender As Object, e As EventArgs) Handles lstNumero.SelectedIndexChanged
        If lstNumero.SelectedIndex < 0 Then
            Dim seleccion = (lstNumero.SelectedText).ToUpper
            Dim index As Integer = listaPrueba.FindIndex(Function(value As Integer) value = seleccion)
            If index < 0 Then
                labCategoria.Text = ""
                labNombre.Text = ""
                labHabilidad.Text = ""
                labNumero.Text = ""
                txtEntrada.Text = "Pokemon no encontrado"
            Else
                Indice = index
            End If
        Else
            Indice = lstNumero.SelectedIndex
        End If
    End Sub

    Private Sub Button4_Click(sender As Object, e As EventArgs) Handles btnSonido.Click
        cargarSonido(Indice)
    End Sub

    Private Sub btnSalir_Click(sender As Object, e As EventArgs) Handles btnSalir.Click
        End
    End Sub

    Private Sub lstNumero_TextChanged(sender As Object, e As EventArgs) Handles lstNumero.TextChanged
        Dim z As String()
        Try
            z = Filter(listaPokemones, lstNumero.Text,, vbTextCompare)
            Indice = Array.IndexOf(listaPokemones, z)
        Catch ex As Exception
            picImagen.Image = My.Resources.Interrogacion
            picTipo1.Image = Nothing
            picTipo2.Image = Nothing
            labCategoria.Text = ""
            labNombre.Text = ""
            labHabilidad.Text = ""
            labNumero.Text = ""
            txtEntrada.Text = "Pokemon no encontrado"
        End Try
    End Sub



#End Region

End Class
